# Model Building:
 Here I have taken last 50000 data points for making the model. As above this much of data points were giving out of memory error. I have choosen the last data points as the were provided and had no  nan values. I know by doing that we wont be able to predict for other places exceple last coordinates but for sake of simplisity i did this.

In [1]:
# !pip install cdsapi

In [2]:
# !pip install xarray

In [6]:
# Import cdsapi
import cdsapi
# Open a new Client instance
c = cdsapi.Client()
# Send your request (download data)
c.retrieve('reanalysis-era5-land', {
        
        'variable':     ('2m_temperature','total_precipitation','volumetric_soil_water_layer_1'),
        'year':         '2019',
        'month':        '12',
        'day':          ('01','02','03','04','05','06','07'),
        'time':         '12:00',
        'format': 'netcdf'

    }, 'data2.nc')



2020-12-23 09:34:30,867 INFO Welcome to the CDS
2020-12-23 09:34:30,869 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-land
2020-12-23 09:34:31,064 INFO Request is completed
2020-12-23 09:34:31,065 INFO Downloading https://download-0015.copernicus-climate.eu/cache-compute-0015/cache/data6/adaptor.mars.internal-1608532590.4132662-11316-3-2c874aa0-d95e-4705-811a-708685a097a4.nc to data2.nc (259.7M)
2020-12-23 09:34:59,823 INFO Download rate 9M/s


Result(content_length=272334400,content_type=application/x-netcdf,location=https://download-0015.copernicus-climate.eu/cache-compute-0015/cache/data6/adaptor.mars.internal-1608532590.4132662-11316-3-2c874aa0-d95e-4705-811a-708685a097a4.nc)

# Data Pre-processing

In [7]:
import xarray as xr

xdata = xr.open_dataset('/content/data2.nc')

In [8]:
xdata

<xarray.Dataset>
Dimensions:    (latitude: 1801, longitude: 3600, time: 7)
Coordinates:
  * longitude  (longitude) float32 0.0 0.1 0.2 0.3 ... 359.6 359.7 359.8 359.9
  * latitude   (latitude) float32 90.0 89.9 89.8 89.7 ... -89.8 -89.9 -90.0
  * time       (time) datetime64[ns] 2019-12-01T12:00:00 ... 2019-12-07T12:00:00
Data variables:
    t2m        (time, latitude, longitude) float32 ...
    tp         (time, latitude, longitude) float32 ...
    swvl1      (time, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2020-12-21 06:36:38 GMT by grib_to_netcdf-2.16.0: /opt/ecmw...

In [21]:
# filled = xdata.interpolate_na(dim="longitude",max_gap=None)
# filled1 = filled.interpolate_na(dim="latitude")
filled2 = xdata['t2m'].interpolate_na(dim="time",max_gap=None,use_coordinate=True)

In [20]:
filled2.isnull()

<xarray.DataArray 't2m' (time: 7, latitude: 1801, longitude: 3600)>
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       ...,

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]]])
Coordinates:
  * longitude  (longitude) float32 0.0 0.1 0.2 0.3 ... 359.6 359.7 359.8 359.9
  * latitude   (latitude) float32 90.0 89.9 89.8 89.7 ... -89.8 -89.9 -90.0
  * time       (time) datetime64[ns] 2019-12-01T12:00:00 ... 2019-12-07T12:00:00

In [ ]:
type(xdata)

xarray.core.dataset.Dataset

In [ ]:
df = xdata.to_dataframe()

In [ ]:
import pandas as pd
pd.pandas.set_option('display.max_columns',None)
pd.pandas.set_option('display.max_rows',None)

df.head(500)

t2m  tp  swvl1
latitude longitude time                               
90.0     0.0       2019-12-01 12:00:00  NaN NaN    NaN
                   2019-12-02 12:00:00  NaN NaN    NaN
                   2019-12-03 12:00:00  NaN NaN    NaN
                   2019-12-04 12:00:00  NaN NaN    NaN
                   2019-12-05 12:00:00  NaN NaN    NaN
                   2019-12-06 12:00:00  NaN NaN    NaN
                   2019-12-07 12:00:00  NaN NaN    NaN
         0.1       2019-12-01 12:00:00  NaN NaN    NaN
                   2019-12-02 12:00:00  NaN NaN    NaN
                   2019-12-03 12:00:00  NaN NaN    NaN
                   2019-12-04 12:00:00  NaN NaN    NaN
                   2019-12-05 12:00:00  NaN NaN    NaN
                   2019-12-06 12:00:00  NaN NaN    NaN
                   2019-12-07 12:00:00  NaN NaN    NaN
         0.2       2019-12-01 12:00:00  NaN NaN    NaN
                   2019-12-02 12:00:00  NaN NaN    NaN
                   2019-12-03 12:00:00  NaN NaN    NaN
                   2019-12-04 12:00:00  NaN NaN    NaN
                   2019-12-05 12:00:00  NaN NaN    NaN
                   2019-12-06 12:00:00  NaN NaN    NaN
                   2019-12-07 12:00:00  NaN NaN    NaN
         0.3       2019-12-01 12:00:00  NaN NaN    NaN
                   2019-12-02 12:00:00  NaN NaN    NaN
                   2019-12-03 12:00:00  NaN NaN    NaN
                   2019-12-04 12:00:00  NaN NaN    NaN
                   2019-12-05 12:00:00  NaN NaN    NaN
                   2019-12-06 12:00:00  NaN NaN    NaN
                   2019-12-07 12:00:00  NaN NaN    NaN
         0.4       2019-12-01 12:00:00  NaN NaN    NaN
                   2019-12-02 12:00:00  NaN NaN    NaN
                   2019-12-03 12:00:00  NaN NaN    NaN
                   2019-12-04 12:00:00  NaN NaN    NaN
                   2019-12-05 12:00:00  NaN NaN    NaN
                   2019-12-06 12:00:00  NaN NaN    NaN
                   2019-12-07 12:00:00  NaN NaN    NaN
         0.5       2019-12-01 12:00:00  NaN NaN    NaN
                   2019-12-02 12:00:00  NaN NaN    NaN
                   2019-12-03 12:00:00  NaN NaN    NaN
                   2019-12-04 12:00:00  NaN NaN    NaN
                   2019-12-05 12:00:00  NaN NaN    NaN
                   2019-12-06 12:00:00  NaN NaN    NaN
                   2019-12-07 12:00:00  NaN NaN    NaN
         0.6       2019-12-01 12:00:00  NaN NaN    NaN
                   2019-12-02 12:00:00  NaN NaN    NaN
                   2019-12-03 12:00:00  NaN NaN    NaN
                   2019-12-04 12:00:00  NaN NaN    NaN
                   2019-12-05 12:00:00  NaN NaN    NaN
                   2019-12-06 12:00:00  NaN NaN    NaN
                   2019-12-07 12:00:00  NaN NaN    NaN
         0.7       2019-12-01 12:00:00  NaN NaN    NaN
                   2019-12-02 12:00:00  NaN NaN    NaN
                   2019-12-03 12:00:00  NaN NaN    NaN
                   2019-12-04 12:00:00  NaN NaN    NaN
                   2019-12-05 12:00:00  NaN NaN    NaN
                   2019-12-06 12:00:00  NaN NaN    NaN
                   2019-12-07 12:00:00  NaN NaN    NaN
         0.8       2019-12-01 12:00:00  NaN NaN    NaN
                   2019-12-02 12:00:00  NaN NaN    NaN
                   2019-12-03 12:00:00  NaN NaN    NaN
                   2019-12-04 12:00:00  NaN NaN    NaN
                   2019-12-05 12:00:00  NaN NaN    NaN
                   2019-12-06 12:00:00  NaN NaN    NaN
                   2019-12-07 12:00:00  NaN NaN    NaN
         0.9       2019-12-01 12:00:00  NaN NaN    NaN
                   2019-12-02 12:00:00  NaN NaN    NaN
                   2019-12-03 12:00:00  NaN NaN    NaN
                   2019-12-04 12:00:00  NaN NaN    NaN
                   2019-12-05 12:00:00  NaN NaN    NaN
                   2019-12-06 12:00:00  NaN NaN    NaN
                   2019-12-07 12:00:00  NaN NaN    NaN
         1.0       2019-12-01 12:00:00  NaN NaN    NaN
                   2019-1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 45385200 entries, (90.0, 0.0, Timestamp('2019-12-01 12:00:00')) to (-90.0, 359.8999938964844, Timestamp('2019-12-07 12:00:00'))
Data columns (total 3 columns):
 #   Column  Dtype  
---  ------  -----  
 0   t2m     float32
 1   tp      float32
 2   swvl1   float32
dtypes: float32(3)
memory usage: 736.1 MB


In [ ]:
df.shape[0]

45385200

In [ ]:
print(df.isna().sum()*100/df.shape[0])

df.isna().sum()

t2m      65.869841
tp       65.869841
swvl1    65.869841
dtype: float64


t2m      29895159
tp       29895159
swvl1    29895159
dtype: int64

In [ ]:
df.shape[0]-29895159

15490041

In [ ]:
xdata.data_vars

Data variables:
    t2m      (time, latitude, longitude) float32 nan nan ... 243.09929 243.09929
    tp       (time, latitude, longitude) float32 nan nan nan nan ... 0.0 0.0 0.0
    swvl1    (time, latitude, longitude) float32 nan nan ... 0.2060981 0.2060981

In [ ]:
xdata['t2m']

<xarray.DataArray 't2m' (time: 7, latitude: 1801, longitude: 3600)>
array([[[      nan,       nan, ...,       nan,       nan],
        [      nan,       nan, ...,       nan,       nan],
        ...,
        [241.74199, 241.74199, ..., 241.74199, 241.74199],
        [241.68526, 241.68526, ..., 241.68526, 241.68526]],

       [[      nan,       nan, ...,       nan,       nan],
        [      nan,       nan, ...,       nan,       nan],
        ...,
        [242.84825, 242.84541, ..., 242.84541, 242.84541],
        [242.34476, 242.34476, ..., 242.34476, 242.34476]],

       ...,

       [[      nan,       nan, ...,       nan,       nan],
        [      nan,       nan, ...,       nan,       nan],
        ...,
        [245.39407, 245.39124, ..., 245.39124, 245.39124],
        [244.79839, 244.79839, ..., 244.79839, 244.79839]],

       [[      nan,       nan, ...,       nan,       nan],
        [      nan,       nan, ...,       nan,       nan],
        ...,
        [244.04529, 244.04529, ..., 244.04245, 244.04245],
        [243.09929, 243.09929, ..., 243.09929, 243.09929]]], dtype=float32)
Coordinates:
  * longitude  (longitude) float32 0.0 0.1 0.2 0.3 ... 359.6 359.7 359.8 359.9
  * latitude   (latitude) float32 90.0 89.9 89.8 89.7 ... -89.8 -89.9 -90.0
  * time       (time) datetime64[ns] 2019-12-01T12:00:00 ... 2019-12-07T12:00:00
Attributes:
    units:      K
    long_name:  2 metre temperature

# Model Building

In [ ]:
df2 = df.tail(50000)

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 50000 entries, (-89.9000015258789, 5.699999809265137, Timestamp('2019-12-02 12:00:00')) to (-90.0, 359.8999938964844, Timestamp('2019-12-07 12:00:00'))
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   t2m     50000 non-null  float32
 1   tp      50000 non-null  float32
 2   swvl1   50000 non-null  float32
dtypes: float32(3)
memory usage: 1.1 MB


In [ ]:
df2.head()

t2m        tp     swvl1
latitude   longitude time                                               
-89.900002 5.7       2019-12-02 12:00:00  242.807114  0.000065  0.152049
                     2019-12-03 12:00:00  241.866791  0.000016  0.152049
                     2019-12-04 12:00:00  242.564590  0.000000  0.152049
                     2019-12-05 12:00:00  243.106384  0.000005  0.152049
                     2019-12-06 12:00:00  245.306137  0.000018  0.152049

In [ ]:
df3 = df2
df3.reset_index(inplace=True)


In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   latitude   50000 non-null  float64       
 1   longitude  50000 non-null  float64       
 2   time       50000 non-null  datetime64[ns]
 3   t2m        50000 non-null  float32       
 4   tp         50000 non-null  float32       
 5   swvl1      50000 non-null  float32       
dtypes: datetime64[ns](1), float32(3), float64(2)
memory usage: 1.7 MB


In [ ]:
df3.head()

latitude  longitude                time         t2m        tp     swvl1
0 -89.900002        5.7 2019-12-02 12:00:00  242.807114  0.000065  0.152049
1 -89.900002        5.7 2019-12-03 12:00:00  241.866791  0.000016  0.152049
2 -89.900002        5.7 2019-12-04 12:00:00  242.564590  0.000000  0.152049
3 -89.900002        5.7 2019-12-05 12:00:00  243.106384  0.000005  0.152049
4 -89.900002        5.7 2019-12-06 12:00:00  245.306137  0.000018  0.152049

In [ ]:
import datetime
df3['time'] = df3['time'].apply(lambda x: x.strftime('%Y-%m-%d %H:%M:%S'))
df3.head()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


latitude  longitude                 time         t2m        tp     swvl1
0 -89.900002        5.7  2019-12-02 12:00:00  242.807114  0.000065  0.152049
1 -89.900002        5.7  2019-12-03 12:00:00  241.866791  0.000016  0.152049
2 -89.900002        5.7  2019-12-04 12:00:00  242.564590  0.000000  0.152049
3 -89.900002        5.7  2019-12-05 12:00:00  243.106384  0.000005  0.152049
4 -89.900002        5.7  2019-12-06 12:00:00  245.306137  0.000018  0.152049

In [ ]:
df4 = df3.drop(['time'],axis=1)
df4.head()

latitude  longitude         t2m        tp     swvl1
0 -89.900002        5.7  242.807114  0.000065  0.152049
1 -89.900002        5.7  241.866791  0.000016  0.152049
2 -89.900002        5.7  242.564590  0.000000  0.152049
3 -89.900002        5.7  243.106384  0.000005  0.152049
4 -89.900002        5.7  245.306137  0.000018  0.152049

In [ ]:
cols = ['latitude','longitude']
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

for i in cols:
    df4[i]=label_encoder.fit_transform(df4[i])

In [ ]:
df4.head()

latitude  longitude         t2m        tp     swvl1
0         1         57  242.807114  0.000065  0.152049
1         1         57  241.866791  0.000016  0.152049
2         1         57  242.564590  0.000000  0.152049
3         1         57  243.106384  0.000005  0.152049
4         1         57  245.306137  0.000018  0.152049

In [ ]:
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader
from sklearn.preprocessing import StandardScaler
import torch.nn.functional as F
from torch.autograd import Variable

In [ ]:
SEED = 42

data = df4.copy()
y = data['tp']
x = data.drop(['tp'],axis=1)


from sklearn.model_selection import train_test_split
x_train,x_val,y_train,y_val = train_test_split(x,y,test_size = 0.2,random_state = SEED)

In [ ]:
type(x_train)

pandas.core.frame.DataFrame

In [ ]:
x_train= np.array(x_train,dtype='float32')
y_train= np.array(y_train,dtype='float32')
x_val= np.array(x_val,dtype='float32')
y_val= np.array(y_val,dtype='float32')

In [ ]:
y_train2=y_train.reshape(40000,-1)
y_train2.shape

(40000, 1)

In [ ]:
sc_x = StandardScaler()
x_train_scaled = sc_x.fit_transform(x_train)
x_test_scaled = sc_x.transform(x_val)

sc_y = StandardScaler()
y_train_scaled = sc_y.fit_transform(y_train2)
# y_test_scaled = sc_y.transform(y_val)

In [ ]:
x_train_scaled

array([[-0.99074286,  0.21692273, -0.9670291 ,  0.32396063],
       [-0.99074286, -0.9185133 , -0.5402979 ,  0.32396063],
       [-0.99074286,  1.0740751 , -0.5402979 ,  0.32396063],
       ...,
       [-0.99074286,  0.08796202, -0.6807619 ,  0.32396063],
       [ 1.0093436 , -1.5875576 , -0.94830537, -3.1596744 ],
       [ 1.0093436 ,  0.48066193, -0.3570328 ,  2.1902153 ]],
      dtype=float32)

In [ ]:
x_train3 = torch.from_numpy(x_train_scaled).requires_grad_()
y_train3 = torch.from_numpy(y_train_scaled).requires_grad_()

In [ ]:
y_train3.shape

torch.Size([40000, 1])

In [ ]:
batch_size = 64
train_ds = TensorDataset(x_train3, y_train3)
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [ ]:
class LinearRegression(nn.Module):
    def __init__(self,input_size,hidden,output_size):
        # super function. It inherits from nn.Module and we can access everythink in nn.Module
        super(LinearRegression,self).__init__()
        # Linear function.
        self.linear1 = nn.Linear(input_dim,40)
        # self.relu1 = nn.ReLU()
        self.tanh1 = nn.Tanh()
        self.linear2 = nn.Linear(40,20)
        # self.relu2 = nn.ReLU()
        self.tanh2 = nn.Tanh()
        self.linear3 = nn.Linear(20,hidden)
        # self.drop = nn.Dropout(0.3)
        self.tanh3 = nn.Tanh()
        self.linear4 = nn.Linear(hidden,output_size)

    def forward(self,x):
      x = self.linear1(x)
      x = self.tanh1(x)
      x = self.linear2(x)
      x = self.tanh2(x)
      x = self.linear3(x)
      x = self.tanh3(x)
      x = self.linear4(x)
      # return x.squeeze()
      return x.squeeze()
    
# define model
input_dim = 4
hidden=10
output_dim = 1
our_model = LinearRegression(input_dim,hidden,output_dim) # 


In [ ]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [ ]:
device

device(type='cuda', index=0)

In [ ]:
# our_model = SimpleNet() 
our_model.to(device)

# criterion = torch.nn.MSELoss(size_average = False) 
loss_fn = F.mse_loss
optimizer = torch.optim.Adam(our_model.parameters(), lr = 0.00001)

In [ ]:
y_train3.shape

torch.Size([40000, 1])

In [ ]:
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
      x_train1 = Variable(x_train3.cuda())
      y_train1 = Variable(y_train3.cuda())
      # Generate predictions
      pred = model(x_train1)
      loss = loss_fn(pred, y_train1)
      # Perform gradient descent
      loss.backward()
      opt.step()
      opt.zero_grad()
    # print('Training loss: ', loss_fn(model(x_train1), y_train1))
    if (epoch+1) % 10 == 0:

      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [ ]:
for xb,yb in train_dl:
  print(xb.shape)
  # print(type(yb))
  break

torch.Size([64, 4])


In [ ]:
torch.cuda.is_available()

True

In [ ]:
fit(500, our_model, loss_fn, optimizer)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: Using a target size (torch.Size([40000, 1])) that is different to the input size (torch.Size([40000])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  import sys


Epoch [500/500], Loss: 1.0427


In [ ]:
x_val = torch.from_numpy(x_test_scaled)
y_val2=y_val.reshape(10000,-1)
y_val3 = sc_y.transform(y_val2)
y_test_scaled = torch.from_numpy(y_val3)

In [ ]:
preds = our_model(x_val.to('cuda'))
# preds = the_model(x_val.to('cuda')).data.cpu() IF ABOVE CODE DONT WORK PLESE TRY THIS OUT

In [ ]:
preds

tensor([[-0.1262],
        [ 0.0494],
        [ 0.5071],
        ...,
        [-0.2492],
        [-0.2251],
        [ 0.1931]])

In [ ]:
y_test_scaled

tensor([[-0.9364],
        [-0.9364],
        [-0.7705],
        ...,
        [-0.8535],
        [-0.6043],
        [-0.9364]])

In [ ]:
from sklearn.metrics import r2_score
preds1 = preds.cpu()
r2_score(y_test_scaled, preds1.detach().numpy())

-0.041566344325981275

In [ ]:
torch.save(our_model, '/content/model3.pth')


# Future work:
1. We can apply more specific models like tabnet which is specific for tabular data for increasing the model performance.

